services:
  postgres:
    image: postgres:latest
    container_name: postgres_brev_ly
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: brev_ly
    ports:
      - "5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Painel de administração
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
